language: cpp
branches:
  only:
  - "/^master$/"
  - "/^pre-release$/"
cache: ccache
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
install:
- "[ $CC = gcc ] && export CC=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
script:
- mkdir -p build && cd build && cmake .. && make && make test
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: RsXOCfo91K6vRZtIYTVfWtMDM8KNIYUff+qnkg7Z4dufttYgqtvDQ46AS8RqFvJM7FMLokyF4UksTB0iqkwOXJvc4bX0SIIyeqfsp1GPyIT18gfU+eoNxdBvB0hK+8ZkDaUE0YSdcMVm+ogsCGVE8KX0RF81sGdfyQf0Ji4PrS8GG9RDlCo9jVvojHSNCZmATf3hEh+NRmSSxit/wDhjhSEf28LYDpnf3dnkqBn1b/q3ajbAmi4KuYCvTiA0yRBh9rthqdhK9E8+PuHBKKscyZadDUSdhc7XZf+8QNxUqOzXu6SgERZTl1xcUCc2WH+pdgkZ+XWtDJNdfMF+/FpU833Qrf0/M9PPqhw39elhHB4jyvX4SCkqyDTRnE+cszL0ESmCldfJtyLalkrfRDbiUb5FkB0pMjLv99qVr5IJ/hfb92G4yQiaSaACy2cydsP1E3VPNem+0THsnhvt9KBa9UVlSRkxiCOtl1GdBSlx04zAutYizmRe/a3r84NPRIWsSJzKCnAhVBf+HdaKp5B581SO7Rn/OmArYMTonh7lo5HCgmsAEfL7rVJSLAIUGmr+/OayXp8JygEca8GfzXG1/Hn3biFR1UpkgfKNPB+mUsfo7Ey4XEnhsRqaqP2ef690JGL74YLzz11+p5wHzmM9R5gjRC8ZPY/1934wGwk9jGo=
